### ISSUE TITLE
Feature Request : Delete Transaction button within the GUI

### ISSUE THREAD

**Issue by SlendyMilky** [dorianim/money-balancer#1]
Hi, thanks for the project, is there any possibility to delete a transaction from the UI ?

**Comment by dorianim** [comment]
Not yet, but this should be simple to implement :)

**Comment by SlendyMilky** [comment]
Nice

**Comment by marcogiorgio** [comment]
Hi @dorianim ,
more in general I would say that it woul be great if you implemented all the basic CRUD operations, so delete and update as well
Thanks!
