### ISSUE TITLE
[server] consolidate config

### ISSUE THREAD

**Issue by dorianim** [dorianim/money-balancer#9]
The config is currently not handled properly. E.g. there is a panic when no `JWT_SECRET` is defined, but only when it is used in an authenticated route. The panic should occur on startup and prevent the server from starting.
I'd suggest using the [config-rs](https://github.com/mehcode/config-rs) lib for this.

**Comment by detronetdip** [comment]
If this issue is open for contribution I would love to take it.

**Comment by dorianim** [comment]
Cool, yes it is!
Do you have experience with rust?

**Comment by detronetdip** [comment]
NO to very little experience in this but as per the example in the issue I don't think rust will be needed. Hopefully typescript can solve it though I do not know much about the project and open to suggestions.

**Comment by dorianim** [comment]
Nope, this is actually a pure rust thing. This issue refers to the configuration management in the server, which is written in rust.
Sorry, maybe the description was not clear enough.

**Comment by detronetdip** [comment]
I misunderstood. sorry for that.

**Comment by dorianim** [comment]
No problem, I'll do it myself then.
